### ISSUE TITLE
Hardcode DARTS feature encoder 

### ISSUE THREAD

**Issue by mikelzc1990** [EvoXGroup/evoxbench#2]
Right now, the [DARTS feature encoder](https://github.com/EvoXGroup/evoxbench/blob/6cbfd9260e37daf2f06544e72de40e8124813aa7/evoxbench/benchmarks/darts.py#L209) is implemented using  [scikit learn onehot encoder](https://github.com/EvoXGroup/evoxbench/blob/6cbfd9260e37daf2f06544e72de40e8124813aa7/evoxbench/benchmarks/darts.py#L6). 

Let's hardcode the DARTS feature encoder (one-hot encoding) and remove the dependency on Scikit Learn.

**Comment by XiaoMingZHM** [comment]
#6 will fix this issue.
